version: '3.8'

services:
  # Zookeeper for Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # MySQL Database
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

  # FastAPI Machine Learning Model
  fastapi-ml:
    build: ./ml_model
    container_name: fastapi-ml
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  # Spring Boot Backend
  spring-boot:
    build: ./backend
    container_name: spring-boot
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql-db

# Define MySQL volume
volumes:
  mysql_data:
